bitcoin:
  network: testnet
  url: "https://distinguished-intensive-frost.btc-testnet.quiknode.pro/38d0f064dc8e72fe44d8a9a762d448bc64c54619/"
  username: ""
  password: ""
  wallet: test_wallet

key_manager:
  network: testnet
  mnemonic_sentence: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
  mnemonic_passphrase: ""

storage:
  password: "secret_password"
  path: /tmp/testnet/wallet/storage.db

wallet:
  db_path: /tmp/testnet/wallet/wallet.db
  start_height: 4734673